# Generated by Django 3.1.7 on 2021-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
